# Generated by Django 5.1.7 on 2025-03-17 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('IDNhanVien', models.AutoField(primary_key=True, serialize=False)),
                ('TenNV', models.CharField(max_length=255)),
                ('SDTNV', models.CharField(max_length=15, unique=True)),
                ('EmailNV', models.EmailField(blank=True, max_length=255, null=True)),
                ('CCCDNV', models.CharField(max_length=20, unique=True)),
                ('ChucVuNV', models.CharField(choices=[('QuanLy', 'Quản lý'), ('PhaChe', 'Pha chế'), ('ThuNgan', 'Thu ngân'), ('PhucVu', 'Phục vụ'), ('BaoVe', 'Bảo vệ')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('SDTNV', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('MatKhauTK', models.CharField(max_length=255)),
            ],
        ),
    ]
