# Generated by Django 5.1.7 on 2025-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafesach', '0002_alter_taikhoan_sdtnv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='ChucVuNV',
            field=models.CharField(choices=[('QuanLy', 'Quản lý'), ('PhaChe', 'Pha chế'), ('ThuNgan', 'Thu ngân'), ('PhucVu', 'Phục vụ'), ('BaoVe', 'Bảo vệ'), ('DonDep', 'Dọn dẹp')], max_length=20),
        ),
    ]
