# Generated by Django 5.1.7 on 2025-03-24 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafesach', '0003_alter_nhanvien_chucvunv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='SDTNV',
            field=models.OneToOneField(db_column='SDTNV', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='SDTNV'),
        ),
    ]
