# Generated by Django 5.1.7 on 2025-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafesach', '0004_alter_taikhoan_sdtnv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='password',
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
