// Types hiện tại cho React Native
export interface OrderItem {
  id: string;
  name: string;
  price: number;
  quantity: number;
  image?: string;
}

export interface Voucher {
  id: string;
  title: string;
  expireDate: string;
  discountValue: string;
  discountType: 'percentage' | 'fixed';
  minimumOrderValue?: number;
  applicableItems?: string[];
}

// Thêm các interface mới cho API Django
export interface SanphamAPI {
  idsanpham: number;
  tensp: string;
  giasp: number;
  trangthaisp: number;
  loaisp: string;
}

export interface VoucherAPI {
  idvoucher: number;
  loaisp: string;
  thoigianbatdauvoucher: string;
  thoigianketthucvoucher: string;
  giamgia: number;
}

export interface DonghoadonAPI {
  idhoadon: number;
  sottdong: number;
  sanpham: number;
  soluongsp: number;
  ghichu?: string;
  voucher?: number;
}
// API OrderHeader interface
export interface APIOrderHeader {
  idhoadon?: number;  // Optional as it will be generated by API
  ngayhd?: string;    // Backend uses auto_now_add=True
  idnhanvien: number | string; // ID of employee creating the order
  tongtien?: number;  // Will be calculated on the backend
  trangthaithanhtoan?: number;
}

// API OrderLine interface
export interface APIOrderLine {
  idhoadon?: number;  // Will be filled in backend
  sottdong?: number;  // Will be filled in backend
  idsanpham: number;
  soluongsp: number;
  ghichu?: string;
  idvoucher?: number | null;
}

// API CompleteOrder interface
export interface APICompleteOrder {
  header: APIOrderHeader;
  lines: APIOrderLine[];
}

// Interface cho nguyên liệu
export interface Ingredient {
  id: number;
  ten_nguyen_lieu: string;
  so_luong: number;
  don_vi: string;
  gia_nhap: number;
}

// Interface cho kết quả API trả về
interface ApiResponse {
  count: number;
  next: string | null;
  previous: string | null;
  results: Ingredient[];
}

// Interface cho đầu vào khi tạo nguyên liệu mới
export interface IngredientInput {
  ten_nguyen_lieu: string;
  so_luong: number;
  don_vi: string;
  gia_nhap: number;
}


export interface Book {
  id: number;
  ten_sach: string;
  tac_gia: string;
  the_loai: string;
  so_luong_sach: number
  trang_thai: string;
}

export interface BookInput {
  ten_sach: string;
  tac_gia: string;
  the_loai: string;
  so_luong_sach: number;
  trang_thai: string;
}

export interface UserInfo {
  SDTNV: string;
  TenNV: string;
  ChucVuNV: number;
  exp?: number;
};