# Generated by Django 5.1.7 on 2025-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, db_column='CheckInTime')),
                ('latitude', models.FloatField(db_column='Latitude')),
                ('longitude', models.FloatField(db_column='Longitude')),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], db_column='Status', max_length=20)),
            ],
            options={
                'db_table': 'chamcong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('idchucvu', models.IntegerField(db_column='idchucvu', primary_key=True, serialize=False)),
                ('loaichucvu', models.CharField(db_column='loaichucvu', max_length=45)),
            ],
            options={
                'db_table': 'chucvu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChucVu_Quyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'chucvu_nhomquyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DongHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sottdong', models.IntegerField(db_column='SoTTDong')),
                ('soluongsp', models.IntegerField(db_column='SoLuongSP')),
                ('ghichu', models.CharField(blank=True, db_column='GhiChu', max_length=255, null=True)),
            ],
            options={
                'db_table': 'donghoadon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id_hoadon', models.AutoField(db_column='IDHoaDon', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hoadon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('IDNhanVien', models.AutoField(db_column='IDNhanVien', primary_key=True, serialize=False)),
                ('TenNV', models.CharField(db_column='TenNV', max_length=255)),
                ('SDTNV', models.CharField(db_column='SDTNV', max_length=15, unique=True)),
                ('EmailNV', models.EmailField(blank=True, db_column='EmailNV', max_length=255, null=True)),
                ('CCCDNV', models.CharField(db_column='CCCDNV', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'nhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhomQuyen',
            fields=[
                ('idnhomquyen', models.CharField(db_column='idnhomquyen', max_length=50, primary_key=True, serialize=False)),
                ('tennhomquyen', models.CharField(db_column='tennhomquyen', max_length=100)),
                ('mota', models.CharField(db_column='mota', max_length=100)),
            ],
            options={
                'db_table': 'nhomquyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhomQuyen_Quyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nhomquyen_quyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quyen',
            fields=[
                ('idquyen', models.CharField(db_column='idquyen', max_length=50, primary_key=True, serialize=False)),
                ('chucnang', models.CharField(db_column='module', max_length=100)),
                ('hanhdong', models.CharField(db_column='action', max_length=100)),
                ('kyhieu', models.CharField(db_column='code', max_length=100)),
            ],
            options={
                'db_table': 'quyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.AutoField(db_column='IDSach', primary_key=True, serialize=False)),
                ('ten_sach', models.CharField(db_column='TenSach', max_length=255, unique=True)),
                ('tac_gia', models.CharField(db_column='TacGia', max_length=255)),
                ('so_luong_sach', models.IntegerField(db_column='SoLuongSach')),
            ],
            options={
                'db_table': 'sach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('idsanpham', models.AutoField(db_column='IDSanPham', primary_key=True, serialize=False)),
                ('tensp', models.CharField(db_column='TenSP', max_length=255)),
                ('giasp', models.DecimalField(db_column='GiaSP', decimal_places=2, max_digits=10)),
                ('trangthaisp', models.IntegerField(db_column='TrangThaiSP')),
                ('loaisp', models.CharField(db_column='LoaiSP', max_length=50)),
            ],
            options={
                'db_table': 'sanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id_tk', models.AutoField(db_column='ID_TK', primary_key=True, serialize=False)),
                ('mat_khau', models.CharField(db_column='MatKhauTK', max_length=255)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.AutoField(db_column='IDTheLoai', primary_key=True, serialize=False)),
                ('ten_the_loai', models.CharField(db_column='TenTheLoai', max_length=255)),
            ],
            options={
                'db_table': 'theloai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TheLoaiCuaSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'theloaicuasach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('idvoucher', models.AutoField(db_column='IDVoucher', primary_key=True, serialize=False)),
                ('tenvoucher', models.CharField(db_column='TenVoucher', max_length=100)),
                ('loaisp', models.CharField(db_column='LoaiSP', max_length=50)),
                ('giamgia', models.IntegerField(db_column='GiamGia')),
                ('thoigianbatdauvoucher', models.DateTimeField(db_column='ThoiGianBatDauVoucher')),
                ('thoigianketthucvoucher', models.DateTimeField(db_column='ThoiGianKetThucVoucher')),
            ],
            options={
                'db_table': 'voucher',
                'managed': False,
            },
        ),
    ]
