# Generated by Django 5.1.7 on 2025-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('id', models.AutoField(db_column='IDNguyenLieu', primary_key=True, serialize=False)),
                ('ten_nguyen_lieu', models.CharField(db_column='TenNguyenLieu', max_length=255)),
                ('so_luong', models.CharField(db_column='SoLuong', max_length=50)),
                ('gia_nhap', models.PositiveIntegerField(db_column='GiaNhap')),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'db_table': 'nguyenlieu',
                'ordering': ['ten_nguyen_lieu'],
            },
        ),
    ]
