# Generated by Django 5.1.7 on 2025-05-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafebook', '0002_nguyenlieu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nguyenlieu',
            options={'managed': False, 'ordering': ['ten_nguyen_lieu'], 'verbose_name': 'Nguyên liệu', 'verbose_name_plural': 'Nguyên liệu'},
        ),
    ]
